apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-secrets
  namespace: multi-tier
  labels:
    app.kubernetes.io/name: multi-tier
    app.kubernetes.io/part-of: cloud-engineer-labs
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: app-secrets
    creationPolicy: Owner
  data:
    - secretKey: DB_USER
      remoteRef:
        key: multi-tier/db
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: multi-tier/db
        property: password
