apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: multi-tier
  labels:
    app.kubernetes.io/name: multi-tier
    app.kubernetes.io/part-of: cloud-engineer-labs
data:
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_NAME: multitierdb
  DB_USER: postgres
